DatabaseDirectory /app/var/clamav
DatabaseOwner appuser
DatabaseMirror database.clamav.net
DNSDatabaseInfo current.cvd.clamav.net
Checks 2
Foreground yes
LogTime yes
ConnectTimeout 30
ReceiveTimeout 120
